# Generated by Django 2.0.4 on 2018-04-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('current_ice', models.IntegerField()),
                ('current_water', models.IntegerField()),
                ('current_low_clouds', models.IntegerField()),
                ('current_high_clouds', models.IntegerField()),
                ('current_rain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('base_ice', models.IntegerField()),
                ('base_water', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='currenttile',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='backend.Map'),
        ),
    ]
