# Generated by Django 2.0.4 on 2018-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttile',
            name='elevation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
